### ISSUE TITLE
Unable to create .o files 

### ISSUE THREAD

**Issue by SethiPawandeep** [mvansegbroeck/featxtra#8]
Hi
Upon copying the files from `feat`, `featbin`, and `transform` directories to the respective directories in `kaldi/src`, and upon running the `make` command, it doesn't create a .o file for `compute-gtf-feats.cc` like there exists one for `compute-mfcc-feats.cc` which is `compute-gtf-feats.o`.

Kindly look into the issue.
Thanks

**Comment by mvansegbroeck** [comment]
What version of Kaldi are you running? The code may be a few versions behind which could give compiling issues.

**Comment by SethiPawandeep** [comment]
Hey
I found a solution for this.
In the directories `feat`, `featbin`, and `transform`, there is a file called `Makefile`. You just need to edit that with the appropriate names of the .cc and .h files.

On doing that and running make command it just throws some more errors. You might have to edit the files to include some other libraries in order to resolve this error.

You should include this in the README that the Makefile in those respective directories needs to be edited.

**Comment by SethiPawandeep** [comment]
So a commit in the kaldi asr project removed the ExtractWaveformRemainder function which is used by your implementation. What is a possible replacement for that?
[This](https://github.com/kaldi-asr/kaldi/commit/1180e467c8ca273c7704199bd27cb734509e931e) is the link to that commit.

**Comment by SethiPawandeep** [comment]
So I basically added the following code
```
void ExtractWaveformRemainder(const VectorBase<BaseFloat> &wave,
                              const FrameExtractionOptions &opts,
                              Vector<BaseFloat> *wave_remainder)
```
from an older version of kaldi (before September 02) to my local repository and made some edits in your files.
I'll be creating a pull request soon so that your code works with the latest kaldi with very minor changes.

Thanks. Closing this issue for now. :)

**Comment by mvansegbroeck** [comment]
Thanks, please do the pull request. 
I appreciate it.
